= Certification

The certification information group is used to state relevant certifications that the candidate has taken.
If a certification requirement is stated, the candidate must have passed the specified exam/test.

== Information specific to CV request

A Contracting Authority can state a certification requirement (main requirement) and an alternative
requirement in the CV request. The alternative requirement is optional, but in some cases other
similar certifications can be accepted. Note that the alternative requirements include the same information elements as the original requirement.

All certifications need to be identified uniquely to ensure that the certification can be referenced in the
CV. The element `cv-req:Requirement` shall be used to differentiate between courses that *should* and *must* be present.

The Contracting Authority can request that the certification must be valid to a specific date (`cv-req:ValidTo`).

.Example of the requested certification for candidate in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=Certification-1]
----
<1> Certification identifier.
<2> Certification requirement - indicate whether a candidate needs to fulfill the certification requirement.  According to codelist Requirement code
<3> Certification title
<4> A date the certification is valid to.

.Example of the requested certification in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=CertificationAlternative]
----
<1> Certification identifier.
<2> Certification requirement - indicate whether a candidate needs to fulfill the certification requirement.  According to codelist Requirement code
<3> Certification title
<4> Certification version.
<5> A date the certification must be valid to.
<6> Alternative certification requirement.

== Information specific to CV

Based on the certification requirement, the Economic Operator needs to document the candidate's certification.

It is possible to state information about the supplier/issuer of the certification. This might be relevant for some Contracting Authorities, since different suppliers may offer the same certification with different content.

.Example of a description of certification in CV as a response to a requested certification in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Certification-1]
----
<1> Certification identifier.
<2> Certification title
<3> Certification version.
<4> A date certification is valid to.
<5> Information about the supplier/issuer of the certification.
<6> The suppliers organisation number. schemeID according to codelist Electronic address identifier (EAID)
<7> The legal name of the supplier.
<8> The country where the supplier is registered - expressed as country code from the codelist.
<9> Contact information for the supplier expressed as email address.
<10> Embedded document as binary object with `mimeCode`. Use Base64.
<11> URI to certification document.
