= Clearance

Jobs within certain departments of the government or private sectors may require that employees
have a security clearance.

== Information specific to CV request

A Contracting Authority can state a clearance requirement if a person shall work with information graded Confidential or higher.

The element `cv-req:Requirement` shall be used to state if the clerarance *should* or *must* be present.

Contracting Authorities must specify the level of clearance (`cv-req:Level`) by using codelist
clearance level. Note that the clearance level is a minimum requirement, which means candidate with
higher level of clearance is qualified.

The Contracting Authority may specify an expiration date (`cv-req:ExpirationDate`), which defines the time period
the clearance needs to be active.

.Example of the requested clearance in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=Clearance]
----
<1> Clearance identifier
<2> Clearance requirement - indicate whether a candidate needs to fulfill the clearance requirement.  According to codelist Requirement code (chapter 5.5).
<3> Clearance level according to codelist Clearance level
<4> Expiration date


== Information specific to CV

Based on the clearance requirement, the Economic Operator needs to document the candidate's
clearance. 
The documentation of clearance can be stated as URI (`cv:ExternalReference/cv:URI`) or embedded document (`cv:EmbeddedDocumentBinaryObject`).

.Example of a description of clearance in CV as a response to requested clearance in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Clearance]
----
<1> Clearance identifier
<2> Clearance level according to codelist Clearance level
<3> Clearance expiration date
<4> Embedded document as binary object with `mimeCode`. Use Base64.
<5> URI to clearance documentation
