= Course

The course information group is used to state relevant courses that the candidate has taken. This information is not mandatory,
but might be relevant for some assignments.

== Information specific to CV request

A Contracting Authority can state a course requirement (main requirement) and an alternative
requirement in the CV request. The alternative requirement is optional, but in some cases other
similar courses can be accepted. As an example the Contracting Authority can accept other versions of the specific course.
Note that the alternative requirements include the same information elements as the original requirement.

All courses need to be identified uniquely to ensure that the course can be referenced in the
CV. The element `cv-req:Requirement` shall be used to differentiate between courses that *should* and *must* be present. The Economic Operators
will only provide qualified candidates, and this makes it easier to do the rating.

In course requirement, the Contracting Authority can specify which period (`cv-req:Period`) the candidate must finish the course. This can
be a date in the future. 

.Example of the requested course in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=Course]
----
<1> Course identifier
<2> Course requirement - indicate whether a candidate needs to fulfill the course requirement.  According to codelist Requirement code
<3> Course title
<4> Period

.Example of the requested course in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=CourseAlternative]
----
<1> Course identifier
<2> Course requirement - indicate whether a candidate needs to fulfill the course requirement.  According to codelist Requirement code
<3> Course title
<4> Course version
<5> Period
<6> Alternative course requirement

== Information specific to CV

Based on the course requirement, the Economic Operator needs to document the candidate's courses.

It is possible to state information about the supplier of the course. This might be relevant for some Contracting
Authorities, since different suppliers may offer the same course with different content.

.Example of a description of course in CV as a response to requested course in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Course]
----
<1> Course identifier
<2> Course title
<3> Course period
<4> Information about the supplier of the course
<5> The supplier's organisation number. schemeID according to codelist Electronic address identifier (EAID)
<6> The legal name of supplier
<7> The country where the supplier is registered - expressed as country code from the codelist
<8> Contact information of supplier expressed as email address
<9> Embedded document as binary object with `mimeCode`. Use Base64.
<10> URI to course document
