= Language skills

Language skills may be specified in CV request and CV. For certain assignments the language skill may be of 
great importance.

== Information specific to CV request

A Contracting Authority can state both a specific language requirement and an alternative requirement.
The alternative requirement is optional, but should be used if an alternative language is accepted.
As an example some Norwegian entities use Norwegian as primarily work language but may accept Swedish and Danish.
There is also possible to require several languages, for example Norwegian and English.
Note that the alternative requirements include the same information elements as the original requirement.

All language skills need to be identified uniquely, to ensure that the language skill can be referenced in the CV.
The element `cv-req:Requirement` shall be used to differentiate between languages skills that *should* and *must* be present.

Oral skill and written skill may be provided for each language skill requirement. The skill levels are based on
EU global standard. Note that the skill level is a minimum requirement. For example, the Contracting Authority wants a candidate
with a `B1` oral skill level. A candidate with an oral skill level of `C1` is above that level and therefore qualified.
Also note that if Scandinavian is set to true, this will overrule the skill requirements between no, sv and da. 

.Example of the requested language skill in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=LanguageSkills]
----
<1> Language skill identifier
<2> Language skill requirement - indicate whether a candidate needs to fulfill the language requirement.  According to codelist Requirement code
<3> A specific language according to codelist ISO639 Language code
<4> Set to true if the language is no, sv or da
<5> Oral skill
<6> Written skill

.Example of the requested language skill in the CV request with alternative requirements
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=LanguageSkillsAlternative]
----
<1> Language skill identifier
<2> Language skill requirement - indicate whether a candidate needs to fulfill the language requirement.  According to codelist Requirement code
<3> A specific language according to codelist ISO639 Language code
<4> Set to true if the language is no, sv or da
<5> Oral skill according to codelist Language level
<6> Written skill according to codelist Language level
<7> Alternative language skill requirements


== Information specific to CV

Based on the language skill requirements, the Economic Operator needs to document the candidate's language skills.
Oral skill and written skill should be provided for each language. The skill levels must be defined according to the
EU global standard codelist.

.Example of a description of language skill in CV as a response to requested language skill in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=LanguageSkills]
----
<1> Language skill identifier
<2> A specific language according to codelist ISO639 Language code
<3> Set to true if the language is no, sv or da
<4> Oral skill according to codelist Language level
<5> Written skill according to codelist Language level
<6> Contact information related to candidate's language skill
