= Skills

Skills contains information about candidate's abilities related to the specific work.

== Information specific to CV request

A Contracting Authority can specify a skill requirement and an alternative requirement in the
CV request. The alternative requirement is optional, but may be used when different skills can be accepted.

The element `cv-req:Requirement` shall be used to differentiate between skills that *should* and *must* be present.

A description of the relevant skill is provided in `cv-req:Type`, ref. examples in chapter below.

The Contracting Authority can specify details about the skill practice directly on `cv-req:Skills`:
the last practiced date (`cv-req:LastPractice`), the skill practice length
(`cv-req:MinimumLengthPractice` - minimum requirement, normally stated as months) and whether the
candidate must provide a reference person (`cv-req:SkillsReference` set to `true`).

.Example of the requested skill in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=Skills]
----
<1> Skill identifier
<2> Skill requirement - indicate whether a candidate needs to fulfill the skill requirement.  According to codelist Requirement code
<3> Type of skill
<4> Last practice date
<5> Length of practice
<6> Skills reference to specify the need for a reference person (true or false)


.Example of the requested skill in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=SkillsAlternative]
----
<1> Skill identifier
<2> Skill requirement - indicate whether a candidate needs to fulfill the skill requirement.  According to codelist Requirement code
<3> Type of skill
<4> Last practice date
<5> Length of practice
<6> Skills reference to specify the need for a reference/contact person (true or false)
<7> Alternative skill requirement


== Information specific to CV

Based on the skill requirement, the Economic Operator must document the candidate's skill. 
The element `cv:Contact` is used to provide contact information to a reference person.

.Example of a description of skill in CV as a response to requested skill in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Skills]
----
<1> Skill identifier
<2> Type of skill
<3> Last practice date
<4> Minimum length of practice
<5> Contact information to reference person

