= Work Experience

Work experience contains information about a candidate's employment history.
This is not the same as project experience.

== Information specific to CV request

A Contracting Authority can specify a request for a work experience in several ways.
For each work experience a position level can be stated, i.e. employee, middle level manager or manager to illustrate
the type of experience a candidate needs for the assignment.

It is also possible to request a work experience specific to a industry or workplace. The job sector can be
specified for each work experience in element `cv-req:JobSector`, e.g. "private".

The minimum total experience can be specified in element `cv-req:MinimumYearsExperience`. This implies that the candidate
must fulfill this requirement and it can be used to differentiate a junior from a senior candidate.

In the CV request, the Contracting Authority can state the requested period for a work experience in element
`cv-req:Period`. This implies that the candidate can only refer to work experience from this period, for example work experience from the last seven years.

The description of experience is provided in element `cv-req:WorkExperienceDescription`, where the candidate's
position percent must be specified in element `cv-req:PositionPercent` (e.g. must have worked 100%, full-time, with the
assignment). The candidate's role (`cv-req:Role`) and the activities performed (`cv-req:Activities`) may also be
described.

.Example of the requested work experience in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=WorkExperience]
----
<1> Work experience identifier
<2> Work experience requirement - indicate whether a candidate needs to fulfill the work experience requirement. According to codelist Requirement code
<3> Position level according to codelist Position level
<4> Type of industry according to codelist Classification of standard industrial classification (NACE)
<5> Workplace according to codelist ISO 3166-1:Alpha2 Country codes
<6> Job sector (private, public or other)
<7> Minimum total years of experience
<8> Period
<9> Position percent
<10> Role in work experience according to code list Classification of Occupations (Styrk98)
<11> Description of work activities

.Example of the requested work experience in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=WorkExperienceAlternative]
----
<1> Work experience identifier
<2> Work experience requirement - indicate whether a candidate needs to fulfill the work experience requirement. According to codelist Requirement code
<3> Position level according to codelist Position level
<4> Type of industry according to codelist Classification of standard industrial classification (NACE)
<5> Workplace according to codelist ISO 3166-1:Alpha2 Country codes
<6> Job sector (private, public or other)
<7> Minimum total years of experience
<8> Period
<9> Position percent
<10> Role in work experience according to code list Classification of Occupations (Styrk98)
<11> Description of work activities
<12> Alternative work experience

== Information specific to CV

Based on the work experience requirement, the Economic Operator needs to document the candidate's work experience.

.Example of a description of work in CV as a response to requested work experience in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=WorkExperience]
----
<1> Work experience identifier
<2> Position level according to codelist Position level
<3> Type of industry according to codelist Classification of standard industrial classification (NACE)
<4> Workplace according to codelist ISO 3166-1:Alpha2 Country codes
<5> Job sector (private, public or other)
<6> Information about company where experience was gained. The company identifier has schemeID according to codelist Electronic address identifier (EAID)
<7> Period for experience
<8> Position percent
<9> Role in work experience according to code list Classification of Occupations (Styrk98)
<10> Description of work activities
<11> Contact information in relevant company
